# Generated by Django 4.1.1 on 2023-02-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='v1',
            new_name='variant1',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='v2',
            new_name='variant2',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='v3',
            new_name='variant3',
        ),
        migrations.AddField(
            model_name='test',
            name='variant4',
            field=models.BooleanField(choices=[('v1', '<django.db.models.fields.CharField>'), ('v2', '<django.db.models.fields.CharField>'), ('v3', '<django.db.models.fields.CharField>')], default=1),
            preserve_default=False,
        ),
    ]
