# Generated by Django 4.1.1 on 2023-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='teacher_photo')),
                ('subject', models.CharField(choices=[('talim', "Ta'lim.Y.K"), ('texnika', 'Texnik.T.A.T'), ('oliy_math', 'Oliy matematika'), ('inglis', 'Inglis-tili'), ('russ', 'Rus-tili')], max_length=80)),
                ('status', models.CharField(choices=[('active', 'Activ'), ('deactive', 'Activ Emas'), ('delete', "O'chirish")], max_length=90)),
                ('created_add', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
