# Generated by Django 4.1.1 on 2023-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='media/teacher_photo'),
        ),
    ]
