# Generated by Django 4.1.1 on 2023-02-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='student_photo')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('deactive', 'Activ Emas'), ('delete', "O'chirish")], max_length=90)),
                ('created_add', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='teacher_photo'),
        ),
    ]
