# Generated by Django 4.1.1 on 2023-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_student_alter_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.CharField(choices=[('one', '⭐'), ('two', '⭐⭐'), ('three', '⭐⭐⭐'), ('four', '⭐⭐⭐⭐'), ('five', '⭐⭐⭐⭐⭐')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stars',
            field=models.CharField(choices=[('one', '⭐'), ('two', '⭐⭐'), ('three', '⭐⭐⭐'), ('four', '⭐⭐⭐⭐'), ('five', '⭐⭐⭐⭐⭐')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
