# Generated by Django 4.1.1 on 2023-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_stars_student_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism familya')),
                ('photo', models.ImageField(upload_to='teacher_photo\\%Y\\%m', verbose_name='Rasm uchun')),
                ('subject', models.CharField(choices=[('talim', "Ta'lim.Y.K"), ('texnika', 'Texnik.T.A.T'), ('oliy_math', 'Oliy matematika'), ('inglis', 'Inglis-tili'), ('russ', 'Rus-tili')], max_length=80, verbose_name='Fanlar')),
                ('stars', models.CharField(choices=[('one', '⭐'), ('two', '⭐⭐'), ('three', '⭐⭐⭐'), ('four', '⭐⭐⭐⭐'), ('five', '⭐⭐⭐⭐⭐')], max_length=100, verbose_name='Yulduzlari')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('deactive', 'Activ Emas'), ('delete', "O'chirish")], max_length=90, verbose_name='Holati')),
                ('created_add', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism familya'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='student_photo', verbose_name='Ism familya'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stars',
            field=models.CharField(choices=[('one', '⭐'), ('two', '⭐⭐'), ('three', '⭐⭐⭐'), ('four', '⭐⭐⭐⭐'), ('five', '⭐⭐⭐⭐⭐')], max_length=100, verbose_name='Yulduzlari'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Activ'), ('deactive', 'Activ Emas'), ('delete', "O'chirish")], max_length=90, verbose_name='Holati'),
        ),
    ]
