# Generated by Django 4.1.1 on 2023-02-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_teacher_delete_post_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teacher_photo', verbose_name='Rasm uchun'),
        ),
    ]
